### ISSUE TITLE
Access Denied, Whierd!

### ISSUE THREAD

**Issue by ScaryPancake** [VirtueDev/Synced#1]
Something or somebody broke me. Everytime I log in I can't edit my profile, check my stuff/mail, buy stuff or anything. And when I refresh the page I get logged out. I was fine earlier today until someone used an autobooter and I got kicked. I am on Chrome. Don't tell me to switch browsers because Firefox can't load Synced and I don't like any other browser. I told TWSICommunity about this but he was useless (he wouldn't really listen). I am also not clearing my cache because I did that already.

Browser: Chrome
OS: Windows 10
Synced Build. 2016-09-04 19:54:10

**Comment by Shadowsych** [comment]
Hi, can you please link me your Synced Account. It is possible that we machine banned your account for not following the Synced Terms and Agreements, so we need to check.

**Comment by ScaryPancake** [comment]
http://www.syncedonline.com/#people-61

**Comment by Shadowsych** [comment]
Try clearing your cookies.

**Comment by ScaryPancake** [comment]
Thanks. For some reason I never had that checked.
